export const UPDATE_DATE_STATE = 'UPDATE_DATE_STATE';
export const UPDATE_NUMBER_DAYS = 'UPDATE_NUMBER_DAYS';

export const FETCH_COST = 'FETCH_COST';
export const FETCH_COST_SUCCESS = 'FETCH_COST_SUCCESS';
export const FETCH_COST_ERROR = 'FETCH_COST_ERROR';
